### ISSUE TITLE
Content negotiation is not called for RPC and REST services

### ISSUE THREAD

**Issue by jguittard** [zfcampus/zf-apigility-admin-ui#32] opened 2015-04-16 11:19 UTC
For RPC and REST services, the call to api.getContentNegotiation is made after service fetch is done, while it should belong to the callback.

**Comment by ezimuel** [comment] 2015-04-16 11:28
@jguittard why this is an issue? The content negotiation has a different API call than the RPC/REST call. It should be fine to have it in a separate event, even because all these services are executed by `initGeneral` function.

**Comment by jguittard** [comment] 2015-04-16 12:16
But upon getContentNegotiation, in the RPC controller, there’s a condition on vm.rpc defined, which is true only after the service responded.
I submitted this PR : https://github.com/zfcampus/zf-apigility-admin-ui/pull/33 <https://github.com/zfcampus/zf-apigility-admin-ui/pull/33>

If you could review it and tell me if that’d work. 

Thank you.

Julien.

**Comment by jguittard** [comment] 2015-04-16 12:24
Context : you created a service (RPC or REST). When you display the page for service details, content negotiation selector list is missing for RPC and not matched for REST

**Comment by ezimuel** [comment] 2015-04-16 16:06
@jguittard Ok, I was able to reproduce the issue and I merged the PR #33 , thanks!

**Closed by ezimuel** 2015-04-16 16:06 UTC
