### ISSUE TITLE
Controller 'ngModel', required by directive 'toggleSwitch', can't be found!

### ISSUE THREAD

**Issue by curtiskelsey** [zfcampus/zf-apigility-admin-ui#101] opened 2016-02-08 21:56 UTC
Found in version 1.2.2, When adding options to a Zend\I18n\Validator\Alnum validator, toggleSwitch does not load. Occurs in Zend\I18n\Validator\Alpha as well. It may be broken across all validator options. I have not confirmed this, however.

**Comment by spectravp** [comment] 2016-02-12 01:11
+1  Same here

**Comment by spectravp** [comment] 2016-02-17 18:35
Hope they fix this soon. It makes it nearly unusable.

**Comment by hoebbelsB** [comment] 2016-02-19 10:15
+1

**Comment by Zbintiosul** [comment] 2016-02-28 21:34
+1

**Comment by spectravp** [comment] 2016-03-03 15:12
Ugh... this is a duplicate of this issue from Oct 2015, https://github.com/zfcampus/zf-apigility-admin-ui/issues/90

**Comment by saulotoledo** [comment] 2019-11-27 14:33
This was fixed in 1.2.4. https://github.com/zfcampus/zf-apigility-admin-ui/issues/90 is also closed.
I could not replicate the issue. @michalbundyra, I believe this can be closed.

**Comment by michalbundyra** [comment] 2019-11-27 14:36
Thanks, @saulotoledo!

**Closed by michalbundyra** 2019-11-27 14:36 UTC
