### ISSUE TITLE
Fail to display rest service configuration which has underscores into the name 

### ISSUE THREAD

**Issue by simonbaudry** [zfcampus/zf-apigility-admin-ui#108] opened 2016-04-01 12:29 UTC
For some reasons, it seems that the request generated to get the rest service data converts the service name like CamelCase and deletes the underscores.

Digging into the code, i saw that the `capitalizeFirstLetter` function in `src/apigility-ui/service/api.service.js` file has been modified by #100 and could be the reason of the bug.

**Comment by colinkelly** [comment] 2016-10-28 08:53
Can you prove it in order to help the investigation? A screenshot of error messages or logs would be good to help this...

Is it admin-UI or admin the proper repo to report to?

**Comment by simonbaudry** [comment] 2016-10-28 16:04
The repo to report it is admin-UI.

You are right I should have given more details about the issue when i saw it.
I tried to reproduce it without success, I guess it has been resolved since last April.

**Comment by colinkelly** [comment] 2016-10-29 02:06
Since you cannot reproduce the issue, I guess we can close this issue.

Thanks for your update by the way ;)

**Closed** 2016-10-31 11:19 UTC
