### ISSUE TITLE
Creation of one HTTP Digest  Authentication Adapter breaks the following new adapters

### ISSUE THREAD

**Issue by elenag77** [zfcampus/zf-apigility-admin-ui#50] opened 2015-05-07 14:51 UTC
Scenario:
1. Create Apigility 1.1 project
2. Open Apigility UI -> Authentication
3. Create new HTTP Digest Adapter 
4. Create new HTTP Digest/HTTP Basic Adapter 

Result:
Notification "Authentication Adapter created" occurred, but the new adapter is broken without name and type. When you click edit in the "Edit  Authentication Adapter" window most of the elements are missing (please see the attached files).
![1](https://cloud.githubusercontent.com/assets/8612477/7517990/ea58e9bc-f4e0-11e4-888c-3427fa0e6d54.jpg)
![2](https://cloud.githubusercontent.com/assets/8612477/7517992/ebe1d988-f4e0-11e4-91c8-e5f8d1155c7f.jpg)

**Comment by ezimuel** [comment] 2015-06-24 15:08
@elenag77 I just tried with a fresh installation, using the master branch, and I cannot reproduce the issue using your steps. I can create multiple HTTP Basic and Digest authentication without issue.
Did you try to update your installation using composer (composer update)?
I'm closing the issue but let me know anyway, thanks for reporting!

**Closed by ezimuel** 2015-06-24 15:08 UTC

**Comment by jmdelehaye** [comment] 2015-07-15 13:26
@see https://github.com/zfcampus/zf-apigility-admin/issues/291#issuecomment-121616104
